<?php

namespace Tests\Feature;

use App\Models\TodoList;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class TodoListTest extends TestCase
{
    use RefreshDatabase;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->list = TodoList::factory()->create(['name' => 'my list']);
    }

    /** @test */
    public function fetch_todo_list()
    {
//        TodoList::factory()->create(['name' => 'my list']);

        $response = $this->getJson(route('todo-list.index'));

        $this->assertEquals(1, count($response->json()));
        $this->assertEquals('my list', $response->json()[0]['name']);

        $response->assertStatus(200);
    }

    /** @test */
    public function fetch_single_todo_list()
    {
        $response = $this->getJson(route('todo-list.show', $this->list->id));
        $this->assertEquals($response->json()['name'], $this->list->name );
        $response->assertStatus(200);
    }
    /** @test */
    public function store_new_todo_list()
    {
        $list = TodoList::factory()->create();
        $response = $this->postJson(route('todo-list.store'), ['name' => $list->name]);

        $response->assertCreated()->json();
        $this->assertEquals($list->name, $response['name']);

        $this->assertDatabaseHas('todo_lists', ['name' => $list->name]);

    }
}
